### ISSUE TITLE
414 URI Too Large on Tx signing

### ISSUE THREAD

**Issue by tijno** [deso-protocol/identity#85]
@maebeam @lazynina 

Ive been running into this lately when trying to buy creator coins.

Had it a week or so ago when trying to buy HighKey

And now it showed up when trying to buy another coin.

![20211022-maSecjwq](https://user-images.githubusercontent.com/69529928/138482870-bf7e9018-c0de-413a-b51a-6d7052c59356.png)

Looks like the tx-hex appended to URL is just too long and nginx throws a 414

https://identity.bitclout.com/approve?tx=a6013966079870ae0326c4740bf39a7de3ac561ceeb364641ce84e253a9c038b6e13005cb3e8442f2b32edbde870c70f5083ebe3c3d98df45171ef6b33e733dc4b225b00b0b60be8eacff7390a7a32f1807159c35a0b38f88b64be6cb562cb599d338ed20113de59906cab306afd0cb049a7943cbb04063baa26f0ab1a3656e25b64b39ddf015ef259dc7c42ba692f14dba49b123e86cf870cf724d00dcdad56ed1fb639bcdf01f3bf4becd1d22b439909fd1f6a54f71e167218d40b2a7940603b73873070b4ef0173062fa31fc4070c11660c45c5a0af423ae9bcb774abb54ddc8f69d6f5a2d80701277564a3606969118063a809d6d0544935da295701675bed520c05c6f71488d20171a0541776c97da3047ec138816919faf12d59376ea3d311eee24612fe59b923011d61ad7385a84692756cd97a41f28285d55c8a48fc1a6948bdb9b5d7bc8159f5013b003ac934a2c5dcb624b386cea57c5f1344f41290ccbbfcd96413dfdbe96c8101660f0dcde9b6464f62de738840825062925f08b157e0e471cf2776e1463603a401b60e94880ed3b8ff1f3d54cbd8dc37829c175d5bc0ef28c0d1319572c92693dd01cff9022ad4d3586201783b8e82bb0d0dc07d084bb42e25f70b731518ebe0945a01c9438e55ef70437230ad9c12da9a8d311a9ada65777576f3690e04cb758d1aa6012fd375f29583a996b770945db201fd0ec96e927ce855884856429843d9b186b501e23d2583123daea74d85222eaa6c1549f1e1efed76a7002b08e3ddd66c916584016e3566d9857ece99427e5524aa149a16719fb71a6d0e92f99e3a906cc4697c21019ceaab284509bdd8483d309bd60ed5860a79fff664527c91eff7ab2e68b6ab6c01f7e7b33e8ba0da2b30f84922f77dec0d448620687d21816efcd00d602af8f18a0111bb0f7f0383ef33bdfdf9343c03ef3fa8fabec2a0ccb2cbe8a5cd42029fc2be01dd4ddf5bc961de39c1e150ed01530ad4551e29b71980eb9f4a849dd77ce76c83014c7d6f9acd502fed5d912482125855507ed155e821b33b2d0cec6b4d583af62600f754b8536f92cfe26601676fb7ed83d011870e9c7fcb7d1f8d92624b6cdf2c3100b0a5ac7d50307cfeea1eecdc92f9de75d33ac2a14b3501c5087588a7277478a600069793ec1e1706dee8f41da75cc9302314627d602d29c0328a49894724a63646008e1885127118418f8dae1833531512bb7827d7875878ca04d59c0533d5cdda8e009125d90ca2314d2f739e1643456827667ec6e8dda1275d4bbd35cd5879530a1a0028f94bca803a4a3323789699bb4fdb029581db89e5a48b881714e1eaea348cd4004f47ec29e32363eb7a70de54b4f74c2854dde0bb5cce8ea48744dc472073755e00c617aa73ed1e7fbb72580c4fbe583c9692e5eed2cf4acd5fda193049681d58be002d43f57c573139d850513dede5529f3321a376257c40a312421ab63b8e0b216b007c5331b9e4c87182a863b6ce4065dbd095bb8a303a419b1563b01caede81d95b0060e77ba6018222339a23a12505fd86d741200275e22cc2a6ada1ffa517b73c54004352b99e12184be92c41d690b89a227129ccd62ae6964ebbc72269493ff1e7d3007cf3c6145836b83796d051b2d2a7da482f958c0ad3b2e3c2f78737a1d593ef2a0055a1c42401adb7c63dccfab051740685476fa9a90be6cf209e570667447d67c500445c624d8197894b007ad505558f990f0636d581d29ada37b1473b3f3f08c5bb006bf57deaf8d262bb29588ed2296e31b2eabd1b27164ca11b7865ee1b3a70cfaa009f36f031b81f87aa9a66fd5e5707e934554221bd73150e102f2defb0becd2bca00fe75e56fc68cf5206cdf05228fc64ce077cd32001ef5003e3a66753cb7ca259b00526128f5f061fe52c520c8f077efb201890e73da052858aa619bb8e8ad717888003e8771d45568e564d7e72680db045253b2e995cb603fe7e1f05970d822ed789b00c107f88563607491860fd8b7522490412b01f49ade21fda18d85ef9874979d73007fde03e59315a6c490be26a5f8374f677e43181d5c1569c2ff4a8740482a1de700b6130d0cd3cec914699e4efcfc2b5c887c4ba08eff7c0143e4b5f481e8fffbe600adf54d13e556e1d27240b83d4c02a6f3c0513ea7e908c55c044ffb30eefb8400009b7e949e1d561d324b8a1c74749dcfd455b973e6452eb5d01ef55b8684a47fc8007029405ea1930652ae85b92d06c70889093568e25c7dff639e44b412086c065c00c39cfb4a4336bd23ed3b380beb89dd36faa23a61956719891b0dd82137bd86fd003b789779e46d2c1e6fb99d2e360c55241ce94df0d753615126307ea0ee7f165800eb7cd629e97aef2cd1985d2d1f55969d6c7ba21371e41f848cbeeaaba163d2db0085f4eac2d2770775d6af1bd245a2ef0c672fb10812321b4150170127758c78830099f1b069a86b5d71aebe0ca5f1924e06b4db514774ca68e82bfe29b1816a2d6e0070f6facb3230956f4f43c52b462367142fefe25b41a8843aaad0738d94f0d66f006c06099bba3970a875117fb65eb1a40c4c471e5f8745ab716727ed2d030a61db005fcaa9bf188ac48320ed9ea4b2dbf981feb61cd2a0dcdc6559e68bd1b3db043500bbb1df78bf63eb5945615f39232ae41737e394d6c0eac260f0f479eed33c88a70077a1abbb6be83ed2ce6b8b1dcd5eafa69cb409cf185565e36ed0c078acc571b5003422c462e2fb8fd679aaa0d32215c49c1175155ffb07b99ac00140f6a2c2d8d9000acb1fd1d7500cde2702d0d4086bb14647458a238772e6d2678a92ac56032375005385c815834828fc3665bea0fc7aae5df2acb9f7201ae1811beff3bd904e6ab000087646c05f1d4286698ac0496a02356e4767f11acc4c808f83bfaacbb424ad5f001d5ec89aa6657a72b5c3e489567bf9fb58c63c3e2c21870f3eec843e844848a300f36f4f59cbcaadeb769e84560a6f0bb1cd1e95926156d8539a103bd55b8cf01600b9225074e1bfe5db3afcff767918b2c019aeec220fa127d315b05c8c446c25d000a25bc848eff8dadeb6a0b4ac65f6f496f55da147761d28182c71f6c77cb93874003978f5ff685fe0875bd254a3841bfb666376b9755a368592151f571ef253f3ce003643dc9e3fd98774908186d10ef2398448e34e23c260ba83663d8ccb99ee1c080036553368c93b31f3f0308b259e7af831674cb5c6e3d44c98f77e64465e51337d00b3d81e5cdbab0596512f75f5e0447a13eea5f8e9da54d66d09f72b24d452b76b009abdde73a60d8da08e36b61cc2e9b9a77091e2fe99fdbc2919f7605c1a9dc09e0077b2d186931a3e3dd311a7d4bccb45742aba4167c9afd01e9d63961d4383047000adce086e23f389c534dccef437e1f328d0188d5ee85c9ea8ddf6c9627b9950be00008d5ce2cb04494f456c27ed9938920489ba59d7ba11131a30d488d71908555500c5025604e83b9518d459cad15c8154c5658a550ed7e48a996bc0f421ec98028b00dfa608162d4ac35355f8de70c9d1168d08a5fb8f13c9551b89dac477bfd3a6040026c92f07515972d68246463417c7f6a2611afd15848c4b190216d8a58463b110000356101fef4e84a01be0635e047dcf260667970890f8edb6479b4ed201007ed400c6fdd66a400fd7da24cf64f83bf975375cf401927c2f5515d1d902f4ac790f90001d59a4d5c60eeec7fc0a1f65811dc0691a62b8cab22db9a6b0413197fe39f2c900faad2dc395484b70fdf6b0827ed50defbee292e949db72b92babefbce7d0914f00ee87865f9ca3a018c7db81ca2c907df0ed6e8056aaf25cc252be325de68ee1d100388d692b2cc7145b8012428c5748a433ade1d7a7f9e13addc5382503526cf468006d599e4192997b31c36dad39a4831c651e9d2d455c39eca1d75d63b1dfec9fd00008489c5bdf99643151d74cec80059548bee613440fd7b5639e6f2039d7edde950046986fca5bddbfb8e4d658fa92181f0af4ca7d5164f2f170d065163c94acfedf0020b8438797e6e103af3b52fa1c1132dffc8e44ac67a44851ccfcfb2be029b8950044871eb2e5e6783742b0eefcbdd28f1dd3bfa1f059c2467c3c7f062e7831ae4900b1fb70ef5d0884f181fb8393d5e245cccdba9f5e57933071cea06924a6132ed9008a8de46df45726c9080bf3669a93f3c84db43e07be84df730c9b47cb12e1ea350041293304ce1977d3f9d104e57c4352c27190966d2652cc3756fa672d2da105430004ae4952fef7a84b90dace59e073c6edca988ccaf7dd869f6c9be91c3d8343cf012baf06fc22ce1fff9a62b232ce1cfe127b3bbdb80692cf0ac0bb068bfbc1918a0112fe3d2d671f9d9ea6908b0911396bf32e46dc06c6b95b1b20082733a18d4e510284aa0a79f037d57a31b10cba60423cb152dee580594bcf759e747f37931ba10801f7a13b0e8ecf99c91735b30654c7c0b99380be48e30f4be1f9d1a85a2022f94c018809b0c60ac107a4e2aa1353f43b07ecfe3f29a5b7b81026045c37b6b56eb7630119812c06f4b525d5ce243e7d640a47294fdb99ac19b7e0c1b7d89f45f8dad6540162ec48682b1e5a22696f4e5d3bdc619dd6dad4cdf5b4ff34c481809507d4eeb801603e13302d0b45f40ec2a1542af4bc989191c484c4f6d0a012275351010c0a7701047c41f9d0237292544a4288b95eb3c6688f0398a1509f87ae4c4f2391ac91c90148cae89c7445f525d9886db3ca183a92090b45581c16b8c24546ce7fd3a187a60113f78e138fd9950f359488e7603fca91b223ee715844e2fdeefe4be396c06ca0011c8b6827a91bf8a90810f69cfce87d681e83f198a39f397bf3b669dda659c093011f6a600ca1353b2a689dafc8f918c10ebddaacf6a3831a2ccdf81a937641c1bf0182f071b60f19e6864ed3bfe11c2f6a4bf63cdcf1c4b53fc84015d778a11ec91001130bb79b0a7439413612247b03ec3348ff28d70b37b84be931facc70fa39d33701196486f4f6c6725215a8cf29f997137deaa19e6b4d68a24f7256fb93cfa5560e01d7b85d3cd96958034b2f1b79eedb4fc6d2a2de0a10aaddac77d4d001b65197da0187cd090b32f1dbb815c9a4c09c5f4ceba00d8fc178c6236897d189928e29b91a01335923d43b34ebb41511a0cc7a70a402a7d8d11c4aab6254d22deb9ae74ec43d0167fce1b72aa26a5ef20c521368fa53675834a584afcebca15b0a8593e99805ce01562e93ac7b16fd5d008478868ec1448185ab0e507fd83a204dce429684a7b49e010c56cb22f56deeece860e932031f1d6bc3cf413226eaa5d1c8c3c448fa489af4012bf289cec52b8e793ade2dd333f1b85738f20f254338134cd67032b0ceca49df013ea543719fa7383f6a814d859d94fcd75f14d0b4ba7377aa66b53b80e1f87c6c011609edd41baf6530548267268972bab122cbfe6e8991d15054b17d222b65fb6301332fcb44437732328f90d0958aeec50300ee1ddf5ae3979800c49c7a210df7e1018b22c9e768db2cf02e85054b17a65ac7841c764e326545cf6dd471e3844f50f301b2e351f4a07564768f9fa0e95cd3322638b465362687a5230cdcfd9db49b48cf011beeb7f33b2fcf9c1ededb8878d9afe32699276e20b3f879d1c95fa886b454830143caf59bc17b91fa0db692e2856b57782f4a3e164d6ace2e918b214e49c4b8b801fb680e3c0514c2dec8dcf19eb1df0ea00d215fa70fa1627938c0302bcb1679d4014582770e390f635a7305b536a031ddcbc90dd209d7935cebfeb99cf42eec2a020139bac897366c1953dba7b664b7b628831dcc97bfacac71938335f42236ed65a501aff52ff0880e30dddea48d8f150b0cc3d382fc373f16bbc74d7d5943312d1b3e01c3fa9e3236b1c447ae5244ff496da376255a08a867571d3cfd153713b01c2e9a0138afd5ae0448779d31b05abcfe01a158ce96c6030eb3dff349acab46a1f13dfa01178b0d0ca172a46807554c8d6381bc9955cddba01e4e583ee3fe06dfe9c1fad70191c75cfafc249cffca30cddc3cb617e6d96cb7f3b899a419657f9f7e52aae9b101084f082adc84fbf1e39b56a7b9d5cabb37e6517926476e7599d3790a7e22d95d01bb2f8926430d3374313f1ba0956f9fc770efaa6115e63e5083b5ce626643ac6a01ceb05d218be84763bd9e9f285a11087a90e39c858f9fd3ab6a8db1cf9d68c1f5015fd9060a70b041e5cf14c8659f02ae2dd699c5657bf3c4bd74c1ec55375f35010161024368684221985f1bb0b0dfb9e6508dd2aee2fc832eb1df5f902baa4289b3002ff930967ef1f53a23dd37169e65dc527eea3a3e99ac0da95d2a1c7d455ae77f01ef35a80e1584c3ac487c0d052d1ddfc0b435327a80af34a554d65ff3c71f1c0501a877320d603e853013a8256a509c9c18af9a17f7ac143d1af4c512294d98ca4e003a15ea6ddc1aa81cc266789589af8a7b4693e0c55e99ffc833fbc61926e5d22b00cefa20c4398f68a306dc7e1eda2a786273fdaf6aa58f2a15505721c3a69986b4006fee9eaaa0ae0629705f309180d2c13a26f8d8ca67a2f72a0dd58d40d8edd01d00bf2205680c3c1f5bf695982f6417162f201a352aa2727504b3c18cf28b4decb000ecec523298ab1ce0f054197cc4d0785b0fa6c9240fb2cb901c6113b39c754f1e0031649a9ed6dba92f5c960a4609774315e0e2b6f3b23a5acde599731e400d6d4700f81c391d69662aed242ca6522a31757fb5c213c310e0535bc1cdab29d12e26ef00e47d6f21eaaaafb33d49ed2d7a65cf50498ea8c51498b1337b162125badbf2db00fc71d04b06062a7963fe5c6851e809f41559e9cec51a4e4d2853dc7317cd689100c25c8d69263f7e5ded2c98b7a1eafddbff0069932eb5f34ce1441a5fbdb6545c0035eea4292ee469561c9e90944f2996b49f3e56e01f95bd071545ba08f7c222d10036179bc309ae72c024485fdaed3469b98456cca8ccf14da34a52ce281956bba500e9a41ad7576056894f2c96ffb9500a022f03dcdd7aff9034734ed9c0476be1fd00e3d53e66a25e28a66287488e538cec0bedae877d7c6746275add79762769fdd100d0a7976e5179ef2dedf4a4d8fbbbc850b2ad33fe42d1b575d2b714258358590800844adb1a8e65ad3fd8e72ec452da8ab571382d3ade462dd30eb0c10a0353ed6701c209d0e1abdf159ce98470a9dab1550d89f1331e893f5d702d7e36ff5e4635e5009c98a20b9b5eaaa1823ce01a2135feef441891799150ee6052ebe3165a62864e03736afd0eca01926cc35e36f0314aa0c31a936c055cf900db9b7140b2c45ad76d031900a86e120e80e46830e4708a83ff62ae19378939324029a0b5a9c8511b692902137e6765a625310e2edce4dd146040761f37db4215fbac476872e92e4d5811de018c242333aec670f729f08e223ef8d8815bff1d9c3d093d064db13ad873ea1f2a02b4d8e8a1904e196d9c2c5910e9d99ba8b09aa687586db874ae2cd61dc3a19add0178182f618849d33740155fdef27d3e6c4dcb0c86235ce6df9e9782fbcac5e94a000b6d1be50d7ac891d79485b5cd4351b2b6fb610dde3e756556885c060de28a23000ef8496e0757f19fab76075e377377ed5e43cfe36a926ee319fb3c569360e8f4003a0465742184a9b65ab4396bae54aa43a00ab5800af149f30de9f5f611f0984a000102a9192d6d3fdf38347606e58e96960b4126b6f3c1fb53244032700cdc97a00b18a2c6e8680b302102436bf488c40e25c54fdfb5f9bc3e48b177bff592e535df1f5d773f145cf76b2f00a6a5a48917000000d6c0efb0052102a9192d6d3fdf38347606e58e96960b4126b6f3c1fb53244032700cdc97a00b180000

Increasing Nginx setting `large_client_header_buffers` can resolve this

https://nginx.org/en/docs/http/ngx_http_core_module.html#large_client_header_buffers

default is 4KB

**Comment by maebeam** [comment]
We need to move this to a postmessage. This will also be solved by balance model

**Comment by tijno** [comment]
ive not seen this error return in a long time - pretty sure its a weird edge case - so closing
